### ISSUE TITLE
Profile window is not minimisable and interacting with the main window is not possible while profile is open

### ISSUE THREAD

**Issue by ktaekwon000** [AY2021S1-CS2103T-W11-4/tp#227]
![image](https://user-images.githubusercontent.com/65844703/97774017-7741b400-1b8f-11eb-9327-82988b607180.png)
minimise button is disabled and user is unable to type commands while profile is open

**Comment by eugene3231** [comment]
Intended feature as we don't want the patient's details to change when viewing the profile
