### ISSUE TITLE
References of original AB3 repo still present

### ISSUE THREAD

**Issue by ktaekwon000** [AY2021S1-CS2103T-W11-4/tp#41]
Currently, items such as the Java CI status badge on [README.md](https://github.com/AY2021S1-CS2103T-W11-4/tp/blob/da667183fc9b894d9f93760f30c5f5443243d8a5/README.md) or codecov badge on [index.md](https://github.com/AY2021S1-CS2103T-W11-4/tp/blob/da667183fc9b894d9f93760f30c5f5443243d8a5/docs/index.md) is still linked to the original AB3 repo, not this repo. 

I'll fix this by Friday night.

**Comment by gsmoon97** [comment]
Keep up the good work 👍
