### ISSUE TITLE
Unnecessary documentation present in codebase - docs/tutorials

### ISSUE THREAD

**Issue by ktaekwon000** [AY2021S1-CS2103T-W11-4/tp#45]
Currently, there is a directory of [`docs/tutorials`](https://github.com/AY2021S1-CS2103T-W11-4/tp/tree/b8777cbe34e93de23b119945ee7e725948f07c48/docs/tutorials) that is not relevant to our project any more. I suggest that we remove this directory from our codebase, for organisation.

**Comment by eugene3231** [comment]
Split this issue into another issue: 
Refer to #47
